<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />


<meta name="author" content="Scott Graham" />

<meta name="date" content="2017-09-29" />

<title>Week 03 Questions</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/lumen.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-1.1/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-1.1/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs && document.readyState && document.readyState === "complete") {
   window.setTimeout(function() {
      hljs.initHighlighting();
   }, 0);
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 54px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 59px;
  margin-top: -59px;
}

.section h2 {
  padding-top: 59px;
  margin-top: -59px;
}
.section h3 {
  padding-top: 59px;
  margin-top: -59px;
}
.section h4 {
  padding-top: 59px;
  margin-top: -59px;
}
.section h5 {
  padding-top: 59px;
  margin-top: -59px;
}
.section h6 {
  padding-top: 59px;
  margin-top: -59px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>




<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
  padding-left: 25px;
  text-indent: 0;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">STAT 541 Questions</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="../../">Home</a>
</li>
<li>
  <a href="Week_01_Questions.html">Week 01</a>
</li>
<li>
  <a href="Week_02_Questions.html">Week 02</a>
</li>
<li>
  <a href="Week_03_Questions.html">Week 03</a>
</li>
<li>
  <a href="Week_04_Questions.html">Week 04</a>
</li>
<li>
  <a href="Week_05_Questions.html">Week 05</a>
</li>
<li>
  <a href="Week_06_Questions.html">Week 06</a>
</li>
<li>
  <a href="Week_07_Questions.html">Week 07</a>
</li>
<li>
  <a href="Week_08_Questions.html">Week 08</a>
</li>
<li>
  <a href="Week_09_Questions.html">Week 09</a>
</li>
<li>
  <a href="Week_10_Questions.html">Week 10</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">

<div class="btn-group pull-right">
<button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Week 03 Questions</h1>
<h4 class="author"><em>Scott Graham</em></h4>
<h4 class="date"><em>September 29, 2017</em></h4>

</div>


<p><span class="math display">\[
  \newcommand{\Prob}{\operatorname{P}}
  \newcommand{\E}{\operatorname{E}}
  \newcommand{\Var}{\operatorname{Var}}
  \newcommand{\Cov}{\operatorname{Cov}}
  \newcommand{\se}{\operatorname{se}}
  \newcommand{\re}{\operatorname{re}}
  \newcommand{\ybar}{{\overline{Y}}}
  \newcommand{\phat}{{\hat{p}}}
  \newcommand{\that}{{\hat{T}}}
  \newcommand{\med}{{\tilde{Y}}}
\]</span></p>
<div id="section" class="section level2">
<h2>2.29</h2>
<p>Let <span class="math inline">\(\alpha=0.05\)</span>, and: <span class="math display">\[
  H_{0}: OR = \frac{Odds_{Drug}}{Odds_{Control}} \leq 1
\]</span> <span class="math display">\[
  H_{1}: OR \frac{Odds_{Drug}}{Odds_{Control}} &gt; 1
\]</span></p>
<pre class="r"><code>results_mat &lt;- matrix(nrow = 2, ncol = 2, c(7, 0, 8, 15))
rownames(results_mat) &lt;- c(&quot;Drug&quot;, &quot;Control&quot;)
colnames(results_mat) &lt;- c(&quot;Normalized&quot;, &quot;Not Normalized&quot;)
results_mat</code></pre>
<pre><code>##         Normalized Not Normalized
## Drug             7              8
## Control          0             15</code></pre>
<pre class="r"><code>fisher.test(results_mat, alternative = &quot;greater&quot;)</code></pre>
<pre><code>## 
##  Fisher&#39;s Exact Test for Count Data
## 
## data:  results_mat
## p-value = 0.003161
## alternative hypothesis: true odds ratio is greater than 1
## 95 percent confidence interval:
##  2.645931      Inf
## sample estimates:
## odds ratio 
##        Inf</code></pre>
<p>Since our p-value (0.003161) is <span class="math inline">\(&lt;\alpha\)</span>, we reject our null hypothesis that the odd’s ratios for the drug and the control <span class="math inline">\(=1\)</span>, and assume that the odds ratio is greater than 1.</p>
</div>
<div id="section-1" class="section level2">
<h2>2.31</h2>
<div id="a." class="section level3">
<h3>a.</h3>
<p>Let <span class="math inline">\(\alpha=0.05\)</span>, and: <span class="math display">\[
  H_{0}: OR = \frac{Odds_{Surgery}}{Odds_{Radiation}} = 1
\]</span> <span class="math display">\[
  H_{1}: OR \frac{Odds_{Surgery}}{Odds_{Radiation}} \neq 1
\]</span></p>
<pre class="r"><code>results_mat &lt;- matrix(nrow = 2, ncol = 2, c(21, 15, 2, 3))
rownames(results_mat) &lt;- c(&quot;Surgey&quot;, &quot;Radiation&quot;)
colnames(results_mat) &lt;- c(&quot; Cancer Controlled&quot;, &quot;Cancer Not Controlled&quot;)
results_mat</code></pre>
<pre><code>##            Cancer Controlled Cancer Not Controlled
## Surgey                    21                     2
## Radiation                 15                     3</code></pre>
<pre class="r"><code>fisher.test(results_mat, alternative = &quot;two.sided&quot;)</code></pre>
<pre><code>## 
##  Fisher&#39;s Exact Test for Count Data
## 
## data:  results_mat
## p-value = 0.6384
## alternative hypothesis: true odds ratio is not equal to 1
## 95 percent confidence interval:
##   0.2089115 27.5538747
## sample estimates:
## odds ratio 
##   2.061731</code></pre>
<pre class="r"><code>1 - dhyper(
  x = results_mat[1, 1] - 1
  ,m = sum(results_mat[, 1])
  ,n = sum(results_mat[, 2])
  ,k = sum(results_mat[1, ])
  )</code></pre>
<pre><code>## [1] 0.6384258</code></pre>
<p>Because our p-value (0.6384) <span class="math inline">\(&gt;\alpha\)</span>, we fail to reject our null hypothesis, and assume the odds of controlling cancer are the same if you have surgery or radiation based on the sample. <span class="math display">\[
  P-Value = 
  \sum_{i=18}^{23}p_{i} \leq
  \Prob\left( n_{11} = 21 \right)
\]</span> <span class="math display">\[
  P-Value =
  \Prob\left( n_{11} = a \right) &gt;
  \Prob\left( n_{11} = 21 \right) \implies
  1 - \Prob\left( n_{11} = 20 \right)
\]</span></p>
</div>
<div id="b." class="section level3">
<h3>b.</h3>
<pre class="r"><code>1 -
  phyper(
    q = results_mat[1, 1]
    ,m = sum(results_mat[, 1])
    ,n = sum(results_mat[, 2])
    ,k = sum(results_mat[1, ])) + 0.5*
  dhyper(
    x = results_mat[1, 1]
    ,m = sum(results_mat[, 1])
    ,n = sum(results_mat[, 2])
    ,k = sum(results_mat[1, ]))</code></pre>
<pre><code>## [1] 0.2430911</code></pre>
<p>Because our p-value (0.2431) <span class="math inline">\(&gt;\alpha\)</span>, we fail to reject our null hypothesis, and assume the odds of controlling cancer are the same if you have surgery or radiation based on the sample.</p>
</div>
</div>
<div id="section-2" class="section level2">
<h2>2.39</h2>
<div id="a.-1" class="section level3">
<h3>a.</h3>
<p>True</p>
</div>
<div id="b.-1" class="section level3">
<h3>b.</h3>
<p>True</p>
</div>
<div id="c." class="section level3">
<h3>c.</h3>
<p>False</p>
</div>
<div id="d." class="section level3">
<h3>d.</h3>
<p>True</p>
</div>
<div id="e." class="section level3">
<h3>e.</h3>
<p>False</p>
</div>
</div>
<div id="section-3" class="section level2">
<h2>3.03</h2>
<div id="a.-2" class="section level3">
<h3>a.</h3>
<p><span class="math display">\[
  \E\left[ \Prob\left( Y = 1 \middle| X = x \right) \right] =
  0.00255+0.00109x,
  x = \{0, 0.5, 1.5, 4.0, 7.0\}
\]</span> That is, on average with no alcohol consumption, there is a <span class="math inline">\(0.255\%\)</span> probability of a sex organ malformation. And on average, for each unit increase in <span class="math inline">\(x\)</span> (alcohol consumption), there is a <span class="math inline">\(0.108\%\)</span> increase in the probability of sex organ malformation, based on the sample.</p>
</div>
<div id="b.-2" class="section level3">
<h3>b.</h3>
<p><span class="math display">\[
  \Prob\left( Y = 1 \middle| X = (0, 7.0) \right)=
  0.00255+0.00109x =
  (0.00255+0.00109(0)), 0.00255+0.00109(7.0)) =
  (0.00255, 0.01018) \implies
\]</span> <span class="math display">\[
  RR =
  \frac{\Prob\left( Y = 1 \middle| X = 7.0 \right)}{\Prob\left( Y = 1 \middle| X = 0 \right)} =
  \frac{0.01018}{0.00255} =
  3.992157
\]</span></p>
</div>
</div>
<div id="section-4" class="section level2">
<h2>3.09</h2>
<pre class="r"><code>income.credit &lt;- read_csv(&quot;http://grahamst.at/projects/STAT_541/STAT_541_Assignments/Week_03_Data_3.09.csv&quot;)</code></pre>
<pre><code>## Parsed with column specification:
## cols(
##   Inc = col_integer(),
##   Card = col_integer()
## )</code></pre>
<pre class="r"><code>income.credit</code></pre>
<pre><code>## # A tibble: 100 x 2
##      Inc  Card
##    &lt;int&gt; &lt;int&gt;
##  1    24     0
##  2    27     0
##  3    28     1
##  4    28     1
##  5    28     0
##  6    28     0
##  7    28     0
##  8    29     0
##  9    29     0
## 10    29     0
## # ... with 90 more rows</code></pre>
<pre class="r"><code>income.credit.glm &lt;- glm(Card ~ Inc, data = income.credit, family = &quot;binomial&quot;)
summary(income.credit.glm)</code></pre>
<pre><code>## 
## Call:
## glm(formula = Card ~ Inc, family = &quot;binomial&quot;, data = income.credit)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.8192  -0.6593  -0.5261   0.3394   2.0911  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -3.55611    0.71685  -4.961 7.02e-07 ***
## Inc          0.05318    0.01314   4.047 5.19e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 123.820  on 99  degrees of freedom
## Residual deviance:  96.963  on 98  degrees of freedom
## AIC: 100.96
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<div id="a.-3" class="section level3">
<h3>a.</h3>
<p><span class="math display">\[
  \ln \left( \frac{\Prob\left( Y = 1 \middle| X = x \right)}{1 - \Prob\left( Y = 1 \middle| X = x \right)} \right) =
  -3.5561 + 0.0532x \implies
\]</span> <span class="math display">\[
  \Prob\left( Y = 1 \middle| X = x \right) = 
  \frac{e^{-3.5561 + 0.0532x}}{1+e^{-3.5561 + 0.0532x}}
\]</span></p>
</div>
<div id="b.-3" class="section level3">
<h3>b.</h3>
<p>On average, as the annual income in Lira increase, the probability of owning at least one travel credit card increases as well, based on the sample.</p>
</div>
<div id="c.-1" class="section level3">
<h3>c.</h3>
<p><span class="math display">\[
  \ln \left( \frac{0.5}{1 - 0.5} \right) =
  -3.5561 + 0.0532x \implies
  0 =
  -3.5561 + 0.0532x \implies
  x =
  66.84398 \approx
  66.86
\]</span> When our LHS = 0, we can solve for <span class="math inline">\(x\)</span>, which gives <span class="math inline">\(x\approx 66.86\)</span> million Lira. That is, on average there is a <span class="math inline">\(50\%\)</span> chance of possessing at least one travel credit card when one’s annual income is 66.86 million Lira, based on the sample.</p>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
