---
title: "Chris Sale Splits"
author: "Scott Graham"
date: "December 15, 2017"
output:
  html_document:
    theme: lumen
    toc: true
    toc_depth: 2
    toc_float: true
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

set.seed(5609)

library(knitr, warn.conflicts = FALSE, quietly = TRUE)
library(kableExtra, warn.conflicts = FALSE, quietly = TRUE)
library(tidyverse, warn.conflicts = FALSE, quietly = TRUE)
library(plotly, warn.conflicts = FALSE, quietly = TRUE)
library(magrittr, warn.conflicts = FALSE, quietly = TRUE)

theme_minimal2 <- theme_minimal() %>%  theme_set()
theme_minimal2 <-
  theme_update(
    panel.border = element_rect(
      linetype = "solid"
      ,colour = "grey92"
      ,fill = NA
    )
    ,strip.background = element_rect(
      linetype = "solid"
      ,colour = "grey92"
      ,fill = NA
    )
  )
```

# Introduction

## Data
```{r Data, include=FALSE}
sale_splits <-
  "data/Chris_Sale_Splits.csv" %>% 
  read_csv() %>% 
  mutate(
    Season = as.factor(Season)
    ,Month = as.factor(Month)
  )

sale_splits$Month <- 
  factor(
    x = sale_splits$Month
    ,levels = 
      c(
        "Mar/Apr"
        ,"May"
        ,"Jun"
        ,"Jul"
        ,"Aug"
        ,"Sept/Oct"
      )
  )
```

The data for this quick bit of analysis can be found [here](http://www.fangraphs.com/leaderssplits.aspx?splitArr=&strgroup=month&statgroup=1&startDate=2001-03-01&endDate=2017-11-01&filter=&position=P&statType=player&autoPt=false&players=10603&sort=20,-1&pg=0). What we're looking at is the monthly splits for Chris Sale from 2010-2017, specifically his ERA, WHIP, and xFIP. Note that Fangraphs combines the months March and April, and September and October together.


## Visualizations
```{r Violin Plot}
sale_splits %>%
  ggplot(
    aes(
      x = Month
      ,y = ERA
      ,fill = Month
    )
  ) +
  geom_violin(draw_quantiles = c(0.25, 0.5, 0.75)) +
  geom_point() +
  scale_fill_brewer(
    type = "qual"
    ,palette = "Set2"
  ) +
  labs(title = "Chris Sale ERA Violin Plot")

sale_splits %>%
  ggplot(
    aes(
      x = Month
      ,y = WHIP
      ,fill = Month
    )
  ) +
  geom_violin(draw_quantiles = c(0.25, 0.5, 0.75)) +
  geom_point() +
  scale_fill_brewer(
    type = "qual"
    ,palette = "Set2"
  ) +
  labs(title = "Chris Sale WHIP Violin Plot")

sale_splits %>%
  ggplot(
    aes(
      x = Month
      ,y = `x FIP`
      ,fill = Month
    )
  ) +
  geom_violin(draw_quantiles = c(0.25, 0.5, 0.75)) +
  geom_point() +
  scale_fill_brewer(
    type = "qual"
    ,palette = "Set2"
  ) +
  labs(title = "Chris Sale xFIP Violin Plot")
```


## Kruskal-Wallis Test
```{r K-W Test}
kruskal.test(ERA ~ Month, data = sale_splits)
kruskal.test(WHIP ~ Month, data = sale_splits)
kruskal.test(`x FIP` ~ Month, data = sale_splits)
```


# Linear Regression
```{r Regression}
sale_splits %>% 
  lm(
    ERA ~ Month
    ,data = .
  ) %>% 
  summary()
sale_splits %>% 
  mutate(Month = as.integer(Month)) %>% 
  lm(
    ERA ~ Month
    ,data = .
  ) %>% 
  summary()

sale_splits %>% 
  lm(
    WHIP ~ Month
    ,data = .
  ) %>% 
  summary()
sale_splits %>% 
  mutate(Month = as.integer(Month)) %>% 
  lm(
    WHIP ~ Month
    ,data = .
  ) %>% 
  summary()

sale_splits %>% 
  lm(
    `x FIP` ~ Month
    ,data = .
  ) %>% 
  summary()
sale_splits %>% 
  mutate(Month = as.integer(Month)) %>% 
  lm(
    `x FIP` ~ Month
    ,data = .
  ) %>% 
  summary()
```