---
title: "STAT 541 Final Project Abstract"
author: "Scott Graham"
date: "November 29, 2017"
output:
  html_document:
    theme: lumen
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse, warn.conflicts = FALSE, quietly = TRUE)
library(magrittr, warn.conflicts = FALSE, quietly = TRUE)
theme_minimal2 <- theme_minimal() %>%  theme_set()
theme_minimal2 <-
  theme_update(
    panel.border = element_rect(
      linetype = "solid"
      ,colour = "grey92"
      ,fill = NA
    )
    ,strip.background = element_rect(
      linetype = "solid"
      ,colour = "grey92"
      ,fill = NA
    )
  )
```
\[
  \newcommand{\Prob}{\operatorname{P}}
  \newcommand{\E}{\operatorname{E}}
  \newcommand{\Var}{\operatorname{Var}}
  \newcommand{\Cov}{\operatorname{Cov}}
  \newcommand{\se}{\operatorname{se}}
  \newcommand{\re}{\operatorname{re}}
  \newcommand{\ybar}{{\overline{Y}}}
  \newcommand{\phat}{{\hat{p}}}
  \newcommand{\that}{{\hat{T}}}
  \newcommand{\med}{{\tilde{Y}}}
\]


Sabermetrics, and advanced sports statistics in baseball came into the public eye in the 1970s. Following the release of Money Ball, the public started to take interest in statistics beyond what is reported by most media outlets. Hockey is no exception to this phenomenon, with the emergence of Corsi and Fenwick as a means of judging player performance. Corsi measure the difference in shot attempts a team faces on any given night, and is typically reported as the percentage of shot attempts for over the total number of shot attempts a team faces in a season. Fenwick is similarly, removing blocked shots from the equation. The idea of using periphery statistics such as these as a means of predicting performance is both important for teams and fans, and potentially lucrative with the amount spent on player acquisitions each year. This data set contains the results of 217 games played between two friends in the NHL series of video games created by EA Sports. In this they recorded many statistics about each game played. As such, a LASSO model will be used to predict the outcome of a game based on a variety of measures, including shots, hits, face offs and other similar stats, answering the question on how to better predict the outcome of hockey game. As well a variety of exploratory analysis is done to look at the relationships that exists between the various predictors, in an effort to generate a better model.

Word Count: 244