<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />


<meta name="author" content="Scott Graham" />

<meta name="date" content="2017-12-06" />

<title>Analysis of EA NHL Results</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}

.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->






<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">STAT 541 Final Project</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="../../">Home</a>
</li>
<li>
  <a href="Report.html">Report</a>
</li>
<li>
  <a href="Presentation.html">Presentation</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Analysis of EA NHL Results</h1>
<h4 class="author"><em>Scott Graham</em></h4>
<h4 class="date"><em>December 06, 2017</em></h4>

</div>


<p><span class="math display">\[
  \newcommand{\Prob}{\operatorname{P}}
  \newcommand{\E}{\operatorname{E}}
  \newcommand{\Var}{\operatorname{Var}}
  \newcommand{\Cov}{\operatorname{Cov}}
  \newcommand{\se}{\operatorname{se}}
  \newcommand{\re}{\operatorname{re}}
  \newcommand{\ybar}{{\overline{Y}}}
  \newcommand{\phat}{{\hat{p}}}
  \newcommand{\that}{{\hat{T}}}
  \newcommand{\med}{{\tilde{Y}}}
  \newcommand{\Logit}{{\operatorname{Logit}}}
\]</span></p>
<div id="introduction" class="section level1">
<h1>Introduction</h1>
<div id="data" class="section level2">
<h2>Data</h2>
<ul>
<li>217 Games Played</li>
<li>EA NHL 12, 13, and 17</li>
<li>Tim <span class="math inline">\(\rightarrow\)</span> P1</li>
<li>Randy <span class="math inline">\(\rightarrow\)</span> P2</li>
</ul>
</div>
<div id="explanatory-variables" class="section level2">
<h2>Explanatory Variables</h2>
<ul>
<li>Categorical:
<ul>
<li>Home vs. Away</li>
<li>Scored First</li>
</ul></li>
<li>Discrete:
<ul>
<li>Shots</li>
<li>Hits</li>
<li>Penalty Minutes (PM)</li>
<li>Penalty Shots</li>
<li>Breakaways</li>
<li>Powerplays</li>
<li>Faceoffs Won</li>
<li>Offensive Faceoffs Won</li>
</ul></li>
<li>Continuous:
<ul>
<li>Time of Attack (ToA)</li>
<li>Passing %</li>
</ul></li>
</ul>
</div>
<div id="research-question" class="section level2">
<h2>Research Question</h2>
<p>What periphery (non-goal related) statistics can be used to predict the outcome of a hockey game?</p>
</div>
</div>
<div id="exploratory-analysis" class="section level1">
<h1>Exploratory Analysis</h1>
<div id="game-results" class="section level2">
<h2>Game Results</h2>
<p><img src="Presentation_files/figure-html/Game%20Results-1.png" width="672" /></p>
</div>
<div id="correlation-matrix" class="section level2">
<h2>Correlation Matrix</h2>
<p><img src="Presentation_files/figure-html/Cor%20Matrix-1.png" width="672" /></p>
</div>
<div id="distribution-of-goals" class="section level2">
<h2>Distribution of Goals</h2>
<p><img src="Presentation_files/figure-html/Goal%20Distribution-1.png" width="672" /></p>
</div>
<div id="goal-distribution-by-version" class="section level2">
<h2>Goal Distribution by Version</h2>
<p><img src="Presentation_files/figure-html/Goal%20Distribution%20by%20Version-1.png" width="672" /></p>
</div>
<div id="goals-vs.shots" class="section level2">
<h2>Goals vs. Shots</h2>
<blockquote>
<p>“You miss 100% of the shots you don’t take.” - Wayne Gretzky</p>
</blockquote>
<p><img src="Presentation_files/figure-html/GvS-1.png" width="672" /></p>
</div>
<div id="autocorrelation" class="section level2">
<h2>Autocorrelation</h2>
<p>Autocorrelation measures the correlation between <span class="math inline">\(\left(X_{t-k}, X_{t}\right), t=k, k+1\dots,n\)</span>. It is primarily used in timeseries analysis to measure the tendency for a time series to be mean reverting (negative autocorrelation) or a tendency to go on long runs in one direct or the other (positive autocorrelation). This is primarily used in the analysis of stock returns, but can be applied to any time series.</p>
</div>
<div id="autocorrelation-plot" class="section level2">
<h2>Autocorrelation Plot</h2>
<p><img src="Presentation_files/figure-html/Autocorrelation%20Plot-1.png" width="672" /></p>
</div>
<div id="autocorrelation-model" class="section level2">
<h2>Autocorrelation Model</h2>
<p><span class="math display">\[
  \operatorname{Logit}\left( \text{P1 Wins} \right) =
  \alpha + \beta_{1}\text{Previous Game&#39;s Result}
\]</span></p>
<pre><code>## 
## Call:
## glm(formula = `P1 Win` ~ `P1 Previous Game`, family = binomial, 
##     data = .)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -0.8677  -0.6905  -0.6905  -0.6905   1.7610  
## 
## Coefficients:
##                       Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)            -1.3122     0.1904  -6.891 5.55e-12 ***
## `P1 Previous Game`Yes   0.5294     0.3568   1.484    0.138    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 236.11  on 215  degrees of freedom
## Residual deviance: 233.98  on 214  degrees of freedom
##   (1 observation deleted due to missingness)
## AIC: 237.98
## 
## Number of Fisher Scoring iterations: 4</code></pre>
</div>
<div id="durbin-watson-test" class="section level2">
<h2>Durbin-Watson Test</h2>
<p><span class="math display">\[
  H_{0}: \text{Autocorrelation} = 0
\]</span> <span class="math display">\[
  H_{1}: \text{Autocorrelation} \neq 0
\]</span></p>
<pre><code>## 
##  Durbin-Watson test
## 
## data:  hockey_acf_logit
## DW = 2.024, p-value = 0.8647
## alternative hypothesis: true autocorrelation is not 0</code></pre>
</div>
</div>
<div id="modeling" class="section level1">
<h1>Modeling</h1>
<div id="contingency-table-model" class="section level2">
<h2>Contingency Table Model</h2>
<pre><code>## , , Home = P1
## 
##           Winner
## Scored_1st P1 P2
##         P1 12 12
##         P2  4 23
## 
## , , Home = P2
## 
##           Winner
## Scored_1st P1 P2
##         P1 25 35
##         P2 10 96</code></pre>
</div>
<div id="flatten_ct" class="section level2">
<h2>flatten_ct</h2>
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Scored_1st
</th>
<th style="text-align:left;">
Winner
</th>
<th style="text-align:left;">
Home
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
P1
</td>
<td style="text-align:left;">
P1
</td>
<td style="text-align:left;">
P1
</td>
</tr>
<tr>
<td style="text-align:left;">
P1
</td>
<td style="text-align:left;">
P1
</td>
<td style="text-align:left;">
P1
</td>
</tr>
<tr>
<td style="text-align:left;">
P1
</td>
<td style="text-align:left;">
P1
</td>
<td style="text-align:left;">
P1
</td>
</tr>
<tr>
<td style="text-align:left;">
P1
</td>
<td style="text-align:left;">
P1
</td>
<td style="text-align:left;">
P1
</td>
</tr>
<tr>
<td style="text-align:left;">
P1
</td>
<td style="text-align:left;">
P1
</td>
<td style="text-align:left;">
P1
</td>
</tr>
<tr>
<td style="text-align:left;">
P1
</td>
<td style="text-align:left;">
P1
</td>
<td style="text-align:left;">
P1
</td>
</tr>
</tbody>
</table>
<table class="table table-striped table-hover" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Scored_1st
</th>
<th style="text-align:left;">
Winner
</th>
<th style="text-align:left;">
Home
</th>
<th style="text-align:right;">
n
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
P1
</td>
<td style="text-align:left;">
P1
</td>
<td style="text-align:left;">
P1
</td>
<td style="text-align:right;">
12
</td>
</tr>
<tr>
<td style="text-align:left;">
P1
</td>
<td style="text-align:left;">
P1
</td>
<td style="text-align:left;">
P2
</td>
<td style="text-align:right;">
25
</td>
</tr>
<tr>
<td style="text-align:left;">
P1
</td>
<td style="text-align:left;">
P2
</td>
<td style="text-align:left;">
P1
</td>
<td style="text-align:right;">
12
</td>
</tr>
<tr>
<td style="text-align:left;">
P1
</td>
<td style="text-align:left;">
P2
</td>
<td style="text-align:left;">
P2
</td>
<td style="text-align:right;">
35
</td>
</tr>
<tr>
<td style="text-align:left;">
P2
</td>
<td style="text-align:left;">
P1
</td>
<td style="text-align:left;">
P1
</td>
<td style="text-align:right;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
P2
</td>
<td style="text-align:left;">
P1
</td>
<td style="text-align:left;">
P2
</td>
<td style="text-align:right;">
10
</td>
</tr>
<tr>
<td style="text-align:left;">
P2
</td>
<td style="text-align:left;">
P2
</td>
<td style="text-align:left;">
P1
</td>
<td style="text-align:right;">
23
</td>
</tr>
<tr>
<td style="text-align:left;">
P2
</td>
<td style="text-align:left;">
P2
</td>
<td style="text-align:left;">
P2
</td>
<td style="text-align:right;">
96
</td>
</tr>
</tbody>
</table>
</div>
<div id="regression-models-and-goodness-of-fit-tests" class="section level2">
<h2>Regression Models and Goodness of Fit Tests</h2>
<div id="logit-model" class="section level3">
<h3>Logit Model</h3>
<p><span class="math display">\[
  \operatorname{Logit}\left( \text{P1 Wins} \right) =
  \alpha + \beta_{1}\text{Scored First} + \beta_{2}\text{Home Team}
\]</span></p>
</div>
<div id="log-linear-model" class="section level3">
<h3>Log Linear Model</h3>
<p><span class="math display">\[
  \ln(\mu) =
  \alpha + \beta_{1}\text{Scored First} + \beta_{2}\text{P1 Wins} + \beta_{3}\text{Home Team}
\]</span></p>
</div>
</div>
<div id="regression-models-and-goodness-of-fit-tests-outputs" class="section level2">
<h2>Regression Models and Goodness of Fit Tests Outputs</h2>
<pre><code>##  (Intercept) Scored_1stP2       HomeP2 
##  -0.04539605   1.87687764   0.40057197</code></pre>
<pre><code>## 
## Chi-squared Goodness of Fit Test 
## 
## model: hockey_ct_logit 
## Chi-squared = 0.04855, df = 1, p-value = 0.82561</code></pre>
<pre><code>## 
## G-squared Goodness of Fit Test 
## 
## model: hockey_ct_logit 
## G-squared = 0.04815, df = 1, p-value = 0.82632</code></pre>
</div>
<div id="log-linear-models-and-goodness-of-fit-tests-outputs" class="section level2">
<h2>Log Linear Models and Goodness of Fit Tests Outputs</h2>
<pre><code>##           (Intercept)          Scored_1stP2              WinnerP2 
##            2.50734710           -1.19156361           -0.04539606 
##                HomeP2 Scored_1stP2:WinnerP2   Scored_1stP2:HomeP2 
##            0.70057578            1.87687765            0.31309456 
##       WinnerP2:HomeP2 
##            0.40057197</code></pre>
<pre><code>## 
## Chi-squared Goodness of Fit Test 
## 
## model: hockey_ct_loglin 
## Chi-squared = 0.04855, df = 1, p-value = 0.82561</code></pre>
<pre><code>## 
## G-squared Goodness of Fit Test 
## 
## model: hockey_ct_loglin 
## G-squared = 0.04815, df = 1, p-value = 0.82632</code></pre>
</div>
<div id="full-model" class="section level2">
<h2>Full Model</h2>
<pre><code>##             (Intercept)          `Scored 1st`P2              `P1 Shots` 
##            -9.882439877            -1.964100240             0.013922296 
##              `P2 Shots`               `P1 Hits`               `P2 Hits` 
##            -0.016037708            -0.007771521             0.043845796 
##                `P1 ToA`                `P2 ToA`            `P1 Passing` 
##            -0.209459372            -0.052092628             8.197579923 
##            `P2 Passing`           `P1 Faceoffs`           `P2 Faceoffs` 
##             9.170534901            -0.061719701            -0.066995303 
## `P1 Offensive Faceoffs` `P2 Offensive Faceoffs`                 `P1 PM` 
##             0.072268107             0.071543085             0.050668097 
##                 `P2 PM`         `P1 Powerplays`         `P2 Powerplays` 
##             0.005239128             0.249659414            -0.066562314 
##      `P1 Penalty Shots`      `P2 Penalty Shots`         `P1 Breakaways` 
##             0.226441915            -1.324943617             0.227003485 
##         `P2 Breakaways` 
##            -0.041275380</code></pre>
<ul>
<li>Scored 1st is significant</li>
<li>P1, P2 Passing, and P1 Breakaways all have p-values <span class="math inline">\(&lt;0.10\)</span></li>
</ul>
</div>
<div id="backward-bic" class="section level2">
<h2>Backward BIC</h2>
<p><span class="math display">\[
  \operatorname{Logit}\left( \text{P1 Wins} \right) =
  \alpha + \beta_{1}\text{Scored 1st} + \beta_{2}\text{P1 Powerplays} 
\]</span> <span class="math display">\[
  + \beta_{3}\text{P2 Penalty Shots}
\]</span> <span class="math display">\[
  =
  -0.8114 - 1.7359\text{Scored 1st} + 0.2133\text{P1 Powerplays}
\]</span> <span class="math display">\[
  - 1.5155\text{P2 Penalty Shots}
\]</span> Where: <span class="math display">\[
  \text{Scored 1st} =
  \begin{cases}
    0,\text{ if P1} \\
    1,\text{ if P2}
  \end{cases}
\]</span></p>
<pre><code>## Waiting for profiling to be done...</code></pre>
<pre><code>##                         2.5 %    97.5 %
## (Intercept)        0.21242841 0.9011030
## `Scored 1st`P2     0.08355758 0.3556937
## `P1 Powerplays`    1.04004592 1.4827889
## `P2 Penalty Shots` 0.03360702 0.8073160</code></pre>
</div>
</div>
<div id="lasso" class="section level1">
<h1>LASSO</h1>
<div id="lasso-plot" class="section level2">
<h2>LASSO Plot</h2>
<p><img src="Presentation_files/figure-html/LASSO%20Plot-1.png" width="672" /></p>
</div>
<div id="lasso-coefficients-1se" class="section level2">
<h2>LASSO Coefficients 1se</h2>
<pre><code>## 22 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                                  1
## (Intercept)             -0.8527071
## Scored 1st Boolean (P2) -0.5670376
## P1 Shots                 .        
## P2 Shots                 .        
## P1 Hits                  .        
## P2 Hits                  .        
## P1 ToA                   .        
## P2 ToA                   .        
## P1 Passing               .        
## P2 Passing               .        
## P1 PM                    .        
## P2 PM                    .        
## P1 Powerplays            .        
## P2 Powerplays            .        
## P1 Faceoffs              .        
## P2 Faceoffs              .        
## P1 Breakaways            .        
## P2 Breakaways            .        
## P1 Penalty Shots         .        
## P2 Penalty Shots         .        
## P1 Offensive Faceoffs    .        
## P2 Offensive Faceoffs    .</code></pre>
</div>
<div id="lasso-coefficients-min" class="section level2">
<h2>LASSO Coefficients Min</h2>
<pre><code>## 22 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                                    1
## (Intercept)             -2.103339281
## Scored 1st Boolean (P2) -1.398137226
## P1 Shots                 0.004405199
## P2 Shots                 .          
## P1 Hits                  .          
## P2 Hits                  .          
## P1 ToA                   .          
## P2 ToA                   .          
## P1 Passing               0.903758203
## P2 Passing               0.990987539
## P1 PM                    .          
## P2 PM                    .          
## P1 Powerplays            0.116633884
## P2 Powerplays            .          
## P1 Faceoffs              .          
## P2 Faceoffs              .          
## P1 Breakaways            0.056989459
## P2 Breakaways            .          
## P1 Penalty Shots         .          
## P2 Penalty Shots        -0.497227038
## P1 Offensive Faceoffs    .          
## P2 Offensive Faceoffs    .</code></pre>
</div>
<div id="lasso-average-coefficient" class="section level2">
<h2>LASSO Average Coefficient</h2>
<pre><code>##             (Intercept) Scored 1st Boolean (P2)                P1 Shots 
##           -2.343864e+00           -1.413696e+00            4.576515e-03 
##                P2 Shots                 P1 Hits                 P2 Hits 
##           -2.228331e-05            0.000000e+00            0.000000e+00 
##                  P1 ToA                  P2 ToA              P1 Passing 
##            0.000000e+00            0.000000e+00            1.073199e+00 
##              P2 Passing                   P1 PM                   P2 PM 
##            1.215923e+00            0.000000e+00            5.687496e-05 
##           P1 Powerplays           P2 Powerplays             P1 Faceoffs 
##            1.217150e-01            0.000000e+00           -1.352674e-04 
##             P2 Faceoffs           P1 Breakaways           P2 Breakaways 
##            0.000000e+00            6.276038e-02            0.000000e+00 
##        P1 Penalty Shots        P2 Penalty Shots   P1 Offensive Faceoffs 
##            0.000000e+00           -5.293945e-01            2.589165e-05 
##   P2 Offensive Faceoffs 
##            0.000000e+00</code></pre>
</div>
<div id="lasso-average-lambda" class="section level2">
<h2>LASSO Average Lambda</h2>
<pre><code>## 22 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                                    1
## (Intercept)             -2.291872149
## Scored 1st Boolean (P2) -1.411379910
## P1 Shots                 0.004591247
## P2 Shots                 .          
## P1 Hits                  .          
## P2 Hits                  .          
## P1 ToA                   .          
## P2 ToA                   .          
## P1 Passing               1.033854992
## P2 Passing               1.158818635
## P1 PM                    .          
## P2 PM                    .          
## P1 Powerplays            0.121235931
## P2 Powerplays            .          
## P1 Faceoffs              .          
## P2 Faceoffs              .          
## P1 Breakaways            0.062261956
## P2 Breakaways            .          
## P1 Penalty Shots         .          
## P2 Penalty Shots        -0.525402691
## P1 Offensive Faceoffs    .          
## P2 Offensive Faceoffs    .</code></pre>
</div>
</div>
<div id="results" class="section level1">
<h1>Results</h1>
<div id="model" class="section level2">
<h2>Model</h2>
<ul>
<li>LASSO Average Lambda chosen
<ul>
<li>Scored First</li>
<li>P1 Shots</li>
<li>P1 &amp; P2 Passing</li>
<li>P1 Powerplays</li>
<li>P1 Breakaways</li>
<li>P2 Penalty Shots</li>
</ul></li>
</ul>
<p><span class="math display">\[
  \ln\left( \frac{\text{P1 Wins}}{\text{P2 Wins}} \right) =
  -2.2919 - 1.4114\text{Scored First} + 0.0046\text{P1 Shots}
\]</span> <span class="math display">\[
  + 1.0339\text{P1 Passing} + 1.1588\text{P2 Passing} + 0.1212\text{P1 Powerplays} 
\]</span> <span class="math display">\[
  + 0.0623\text{P1 Breakaways} - 0.5254\text{P2 Penalty Shots}
\]</span></p>
</div>
<div id="interpretation" class="section level2">
<h2>Interpretation</h2>
<ul>
<li><p>By scoring first, a player increases their estimated odds in favour of winning by a multiplicative factor of 4.1016</p></li>
<li>Only P1’s shots was found as a useful predictive measure.
<ul>
<li>Increases the estimated odds in favour by a multiplicative factor of 1.0046 per each additional shot</li>
<li>So not a lot</li>
</ul></li>
<li>If both players make a lot of their passes, P1’s increases their estimated odds in favour of winning by a multiplicative factor of:
<ul>
<li>P1: 2.8119</li>
<li>P2: 3.1862</li>
</ul></li>
<li>The more 1-on-0 opportunities given up in a game by a player, the less likely that player will win.
<ul>
<li>Breakaways: 1.0642</li>
<li>Penalty Shots: 0.5913</li>
</ul></li>
</ul>
</div>
<div id="weaknesses" class="section level2">
<h2>Weaknesses</h2>
<ul>
<li>Based on a video game
<ul>
<li>May not apply to real life</li>
</ul></li>
<li>Who is P1 in real life?
<ul>
<li>Other combinations of players may have different results</li>
</ul></li>
<li>Includes P1’s and P2’s Passing %
<ul>
<li>Both have the same sign</li>
<li>Unexpected</li>
</ul></li>
<li>Possible overfitting
<ul>
<li>Uses <span class="math inline">\(\lambda_{Min}\)</span> instead of <span class="math inline">\(\lambda_{1se}\)</span></li>
</ul></li>
<li><p>Introduced bias to lower variance</p></li>
<li><p>It may be beneficial to use the average coefficient LASSO, with a cutoff if the variable appears in <span class="math inline">\(&lt;x\%\)</span> of results</p></li>
</ul>
</div>
<div id="references" class="section level2">
<h2>References</h2>
<p>Gelman, A. (2014, June 02). Why we hate stepwise regression. Retrieved November 29, 2017, from <a href="http://andrewgelman.com/2014/06/02/hate-stepwise-regression/" class="uri">http://andrewgelman.com/2014/06/02/hate-stepwise-regression/</a></p>
<p>Hastie, T., &amp; Qian, J. (2014, June 26). Glmnet Vignette. Retrieved November 29, 2017, from <a href="https://web.stanford.edu/~hastie/glmnet/glmnet_alpha.html" class="uri">https://web.stanford.edu/~hastie/glmnet/glmnet_alpha.html</a></p>
<p>NHL 18 - EA SPORTS - Official Site. (n.d.). Retrieved November 29, 2017, from <a href="https://www.easports.com/nhl" class="uri">https://www.easports.com/nhl</a></p>
<p>R. (n.d.). 2_buds_hockey_stats.xlsx. Retrieved November 29, 2017, from <a href="http://randude.com/ps3/" class="uri">http://randude.com/ps3/</a></p>
<p>Testing for Autocorrelation. (1999). Retrieved November 29, 2017, from <a href="http://www.okstate.edu/sas/v8/sashtml/ets/chap8/sect5.htm" class="uri">http://www.okstate.edu/sas/v8/sashtml/ets/chap8/sect5.htm</a></p>
<p>Wickham, H. (n.d.). Tidyverse. Retrieved November 29, 2017, from <a href="https://www.tidyverse.org/" class="uri">https://www.tidyverse.org/</a></p>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
