<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />


<meta name="author" content="Scott Graham" />

<meta name="date" content="2017-10-13" />

<title>Week 05 Questions</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/lumen.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-1.1/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-1.1/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs && document.readyState && document.readyState === "complete") {
   window.setTimeout(function() {
      hljs.initHighlighting();
   }, 0);
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 54px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 59px;
  margin-top: -59px;
}

.section h2 {
  padding-top: 59px;
  margin-top: -59px;
}
.section h3 {
  padding-top: 59px;
  margin-top: -59px;
}
.section h4 {
  padding-top: 59px;
  margin-top: -59px;
}
.section h5 {
  padding-top: 59px;
  margin-top: -59px;
}
.section h6 {
  padding-top: 59px;
  margin-top: -59px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>




<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
  padding-left: 25px;
  text-indent: 0;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">STAT 541 Questions</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="../../">Home</a>
</li>
<li>
  <a href="Week_01_Questions.html">Week 01</a>
</li>
<li>
  <a href="Week_02_Questions.html">Week 02</a>
</li>
<li>
  <a href="Week_03_Questions.html">Week 03</a>
</li>
<li>
  <a href="Week_04_Questions.html">Week 04</a>
</li>
<li>
  <a href="Week_05_Questions.html">Week 05</a>
</li>
<li>
  <a href="Week_06_Questions.html">Week 06</a>
</li>
<li>
  <a href="Week_07_Questions.html">Week 07</a>
</li>
<li>
  <a href="Week_08_Questions.html">Week 08</a>
</li>
<li>
  <a href="Week_09_Questions.html">Week 09</a>
</li>
<li>
  <a href="Week_10_Questions.html">Week 10</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">

<div class="btn-group pull-right">
<button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Week 05 Questions</h1>
<h4 class="author"><em>Scott Graham</em></h4>
<h4 class="date"><em>October 13, 2017</em></h4>

</div>


<p><span class="math display">\[
  \newcommand{\Prob}{\operatorname{P}}
  \newcommand{\E}{\operatorname{E}}
  \newcommand{\Var}{\operatorname{Var}}
  \newcommand{\Cov}{\operatorname{Cov}}
  \newcommand{\se}{\operatorname{se}}
  \newcommand{\re}{\operatorname{re}}
  \newcommand{\ybar}{{\overline{Y}}}
  \newcommand{\phat}{{\hat{p}}}
  \newcommand{\that}{{\hat{T}}}
  \newcommand{\med}{{\tilde{Y}}}
\]</span></p>
<div id="section" class="section level2">
<h2>4.09</h2>
<pre class="r"><code>crabs_data &lt;- 
  read_csv(
    file = &quot;http://grahamst.at/projects/STAT_541/STAT_541_Assignments/Week_05_Data_4.09.csv&quot;
  ) %&gt;% 
  mutate(
    satell_bool = if_else(satell &gt; 0, 1, 0)
    ,c1 = if_else(color == 1, 1, 0 )
    ,c2 = if_else(color == 2, 1, 0 )
    ,c3 = if_else(color == 3, 1, 0 )
    ,color = color + 1
  )</code></pre>
<pre><code>## Parsed with column specification:
## cols(
##   color = col_integer(),
##   spine = col_integer(),
##   width = col_double(),
##   satell = col_integer(),
##   weight = col_double()
## )</code></pre>
<div id="a." class="section level3">
<h3>a.</h3>
<pre class="r"><code>logit_reg_4.09a &lt;- glm(satell_bool ~ c1 + c2 + c3, data = crabs_data, family = &quot;binomial&quot;)
summary(logit_reg_4.09a)</code></pre>
<pre><code>## 
## Call:
## glm(formula = satell_bool ~ c1 + c2 + c3, family = &quot;binomial&quot;, 
##     data = crabs_data)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.6651  -1.3370   0.7997   0.7997   1.5134  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  -0.7621     0.4577  -1.665 0.095910 .  
## c1            1.8608     0.8087   2.301 0.021393 *  
## c2            1.7382     0.5123   3.393 0.000692 ***
## c3            1.1299     0.5509   2.051 0.040289 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 225.76  on 172  degrees of freedom
## Residual deviance: 212.06  on 169  degrees of freedom
## AIC: 220.06
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p><span class="math display">\[
  \ln\left( \theta \right) =
  -0.7621 + 1.8608c_{1} + 1.7382c_{2} + 1.1299c_{3}
\]</span> That is, on average for a medium light crab, the log odds in favour increase by 1.8608 compared to a dark crab, based on the sample. Or the average odds in favour increase by a multiplicative factor of <span class="math inline">\(e^{1.8608} = 6.4286\)</span>, based on the sample.</p>
</div>
<div id="b." class="section level3">
<h3>b.</h3>
<pre class="r"><code>pchisq(
  q = logit_reg_4.09a$null.deviance - logit_reg_4.09a$deviance
  ,df = logit_reg_4.09a$df.null - logit_reg_4.09a$df.residual
  ,lower.tail = FALSE
)</code></pre>
<pre><code>## [1] 0.003346919</code></pre>
<p>We therefore reject our null hypothesis that the models have similar levels of deviance, and accept the alternative that they differ, based on the sample. That is, colour does play a role in predicting if a crab has satellites.</p>
</div>
<div id="c." class="section level3">
<h3>c.</h3>
<pre class="r"><code>logit_reg_4.09c &lt;- glm(satell_bool ~ color, data = crabs_data, family = &quot;binomial&quot;)
summary(logit_reg_4.09c)</code></pre>
<pre><code>## 
## Call:
## glm(formula = satell_bool ~ color, family = &quot;binomial&quot;, data = crabs_data)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.9103  -1.2719   0.8142   0.8142   1.3937  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)   3.0781     0.7577   4.062 4.86e-05 ***
## color        -0.7147     0.2095  -3.412 0.000645 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 225.76  on 172  degrees of freedom
## Residual deviance: 213.30  on 171  degrees of freedom
## AIC: 217.3
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p><span class="math display">\[
  \ln\left( \theta \right) =
  3.0781 - 0.7147Colour
\]</span> As you move each step up the colour scale, with 2 being medium light, and 5 being dark, on average the log odds in favour decrease by 0.7147, or the odds decrease by a multiplicative factor of <span class="math inline">\(e^{-0.7147} = 0.4893\)</span>, based on the sample.</p>
</div>
<div id="d." class="section level3">
<h3>d.</h3>
<pre class="r"><code>pchisq(
  q = logit_reg_4.09c$null.deviance - logit_reg_4.09c$deviance
  ,df = logit_reg_4.09c$df.null - logit_reg_4.09c$df.residual
  ,lower.tail = FALSE
)</code></pre>
<pre><code>## [1] 0.0004156143</code></pre>
<p>Therefore we reject the null hypothesis that the models explain the same amount of variance, and accept that the more complicated model is better based on the sample.</p>
</div>
<div id="e." class="section level3">
<h3>e.</h3>
<p>The advantage of quantitative colour, is we set the <span class="math inline">\(df\)</span> in the likelihood ratio test to 1, giving a more powerful test, but if there is a non-linear relationship between colour and the log odds in favour (polynomial, exponential, etc), this model may not capture it.</p>
</div>
</div>
<div id="section-1" class="section level2">
<h2>4.11</h2>
<p><span class="math display">\[
  \frac{\theta_{\text{Spouse}}}{\theta_{\text{Alone}}} =
  2.02,
  \frac{\theta_{\text{Others}}}{\theta_{\text{Alone}}} =
  1.71 \implies
  \frac{\theta_{\text{Spouse}}}{\theta_{\text{Others}}} =
  \frac{2.02}{1.71} =
  1.18
\]</span> <span class="math display">\[
  \frac{\theta_{\text{Medium Income}}}{\theta_{\text{Low Income}}} =
  0.72,
  \frac{\theta_{\text{High Income}}}{\theta_{\text{Low Income}}} =
  0.41 \implies
  \frac{\theta_{\text{High Income}}}{\theta_{\text{Medium Income}}} =
  \frac{0.41}{0.72} =
  0.57
\]</span></p>
</div>
<div id="section-2" class="section level2">
<h2>4.16</h2>
<pre class="r"><code>myers_data &lt;- 
  tibble(
    Personality = c(
      rep(&quot;ESTJ&quot;, times = 10 + 67)
      ,rep(&quot;ESTP&quot;, times = 8 + 34)
      ,rep(&quot;ESFJ&quot;, times = 5 + 101)
      ,rep(&quot;ESFP&quot;, times = 7 + 72)
      ,rep(&quot;ENTJ&quot;, times = 3 + 20)
      ,rep(&quot;ENTP&quot;, times = 2 + 16)
      ,rep(&quot;ENFJ&quot;, times = 4 + 27)
      ,rep(&quot;ENFP&quot;, times = 15 + 65)
      ,rep(&quot;ISTJ&quot;, times = 17 + 123)
      ,rep(&quot;ISTP&quot;, times = 3 + 49)
      ,rep(&quot;ISFJ&quot;, times = 6 + 132)
      ,rep(&quot;ISFP&quot;, times = 4 + 102)
      ,rep(&quot;INTJ&quot;, times = 1 + 12)
      ,rep(&quot;INTP&quot;, times = 5 + 30)
      ,rep(&quot;INFJ&quot;, times = 1 + 30)
      ,rep(&quot;INFP&quot;, times = 6 + 73)
    )
    ,Alcohol = c(
      rep(c(1, 0), times = c(10, 67))
      ,rep(c(1, 0), times = c(8, 34))
      ,rep(c(1, 0), times = c(5, 101))
      ,rep(c(1, 0), times = c(7, 72))
      ,rep(c(1, 0), times = c(3, 20))
      ,rep(c(1, 0), times = c(2, 16))
      ,rep(c(1, 0), times = c(4, 27))
      ,rep(c(1, 0), times = c(15, 65))
      ,rep(c(1, 0), times = c(17, 123))
      ,rep(c(1, 0), times = c(3, 49))
      ,rep(c(1, 0), times = c(6, 132))
      ,rep(c(1, 0), times = c(4, 102))
      ,rep(c(1, 0), times = c(1, 12))
      ,rep(c(1, 0), times = c(5, 30))
      ,rep(c(1, 0), times = c(1, 30))
      ,rep(c(1, 0), times = c(6, 73))
    )
  ) %&gt;% 
  # If the stated letter appears in the personality column, place a 1, 
  # otherwise place a 0.
  mutate(
    `E/I` = if_else(grepl(pattern = &quot;E&quot;, x = Personality), 1, 0)
    ,`S/N` = if_else(grepl(pattern = &quot;S&quot;, x = Personality), 1, 0)
    ,`T/F` = if_else(grepl(pattern = &quot;T&quot;, x = Personality), 1, 0)
    ,`J/P` = if_else(grepl(pattern = &quot;J&quot;, x = Personality), 1, 0)
  )
myers_data</code></pre>
<pre><code>## # A tibble: 1,050 x 6
##    Personality Alcohol `E/I` `S/N` `T/F` `J/P`
##          &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1        ESTJ       1     1     1     1     1
##  2        ESTJ       1     1     1     1     1
##  3        ESTJ       1     1     1     1     1
##  4        ESTJ       1     1     1     1     1
##  5        ESTJ       1     1     1     1     1
##  6        ESTJ       1     1     1     1     1
##  7        ESTJ       1     1     1     1     1
##  8        ESTJ       1     1     1     1     1
##  9        ESTJ       1     1     1     1     1
## 10        ESTJ       1     1     1     1     1
## # ... with 1,040 more rows</code></pre>
<div id="a.-1" class="section level3">
<h3>a.</h3>
<pre class="r"><code>logit_reg_4.16a &lt;- glm(
  Alcohol ~ `E/I` + `S/N` + `T/F` + `J/P`
  ,data = myers_data
  ,family = &quot;binomial&quot;
)
summary(logit_reg_4.16a)</code></pre>
<pre><code>## 
## Call:
## glm(formula = Alcohol ~ `E/I` + `S/N` + `T/F` + `J/P`, family = &quot;binomial&quot;, 
##     data = myers_data)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -0.7179  -0.4775  -0.4036  -0.3279   2.5069  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  -2.4668     0.2429 -10.154  &lt; 2e-16 ***
## `E/I`         0.5550     0.2170   2.558  0.01053 *  
## `S/N`        -0.4292     0.2340  -1.834  0.06663 .  
## `T/F`         0.6873     0.2206   3.116  0.00184 ** 
## `J/P`        -0.2022     0.2266  -0.893  0.37209    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 646.83  on 1049  degrees of freedom
## Residual deviance: 627.49  on 1045  degrees of freedom
## AIC: 637.49
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p><span class="math display">\[
  \ln\left( \theta \right) =
  -2.4668 + 0.5550\text{E/I} - 0.4292\text{S/N} + 0.6873\text{T/F} - 0.2022\text{J/P}
\]</span> Where the first letter for each coefficient is coded as a 1, and the second letter as a 0.</p>
</div>
<div id="b.-1" class="section level3">
<h3>b.</h3>
<pre class="r"><code>predict(
  object = logit_reg_4.16a
  ,newdata = 
    tibble(
    `E/I` = 1
    ,`S/N` = 1
    ,`T/F` = 1
    ,`J/P` = 1
  )
  ,type = &quot;response&quot;)</code></pre>
<pre><code>##        1 
## 0.135186</code></pre>
</div>
<div id="c.-1" class="section level3">
<h3>c.</h3>
<pre class="r"><code>predict(
  object = logit_reg_4.16a
  ,newdata = 
    tibble(
    `E/I` = 1
    ,`S/N` = 0
    ,`T/F` = 1
    ,`J/P` = 0
  )
  ,type = &quot;response&quot;)</code></pre>
<pre><code>##         1 
## 0.2271486</code></pre>
<p>It is the response that has all the positive coefficients set to 1, and the negative coefficients set to 0.</p>
</div>
</div>
<div id="section-3" class="section level2">
<h2>4.17</h2>
<div id="a.-2" class="section level3">
<h3>a.</h3>
<pre class="r"><code>logit_reg_4.17a &lt;- glm(
  Alcohol ~ `E/I` + `T/F`
  ,data = myers_data
  ,family = &quot;binomial&quot;
)
summary(logit_reg_4.17a)</code></pre>
<pre><code>## 
## Call:
## glm(formula = Alcohol ~ `E/I` + `T/F`, family = &quot;binomial&quot;, data = myers_data)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -0.5923  -0.4515  -0.4480  -0.3388   2.4027  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  -2.8291     0.1955 -14.470  &lt; 2e-16 ***
## `E/I`         0.5805     0.2160   2.687  0.00721 ** 
## `T/F`         0.5971     0.2152   2.774  0.00554 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 646.83  on 1049  degrees of freedom
## Residual deviance: 632.74  on 1047  degrees of freedom
## AIC: 638.74
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<pre class="r"><code>predict(
  object = logit_reg_4.17a
  ,newdata = 
    tibble(
    `E/I` = 0
    ,`T/F` = 0
  )
  ,type = &quot;response&quot;)</code></pre>
<pre><code>##          1 
## 0.05576985</code></pre>
</div>
<div id="b.-2" class="section level3">
<h3>b.</h3>
<p><span class="math display">\[
  e^{\beta_{\text{E/I}}} =
  e^{0.5805} =
  1.7869
\]</span> The odds in favour on average increases by a mulitplicative factor 1.7869 for extroverted personalities vs. introverted personalities, based on the sample.</p>
</div>
<div id="c.-2" class="section level3">
<h3>c.</h3>
<pre class="r"><code>confint(object = logit_reg_4.17a, level = 0.95) %&gt;% 
  exp %&gt;% 
  round(4)</code></pre>
<pre><code>## Waiting for profiling to be done...</code></pre>
<pre><code>##              2.5 % 97.5 %
## (Intercept) 0.0396 0.0853
## `E/I`       1.1722 2.7400
## `T/F`       1.1907 2.7747</code></pre>
<p>With 95% confidence, the true value of the conditional odds ratio between E/I and the response lies between 1.1722 and 2.7400 based on the sample.</p>
</div>
<div id="d.-1" class="section level3">
<h3>d.</h3>
<p><span class="math display">\[
  \beta_{\text{I/E}} =
  -\beta_{\text{E/I}} =
  -0.5805 \implies
  e^{\beta_{\text{I/E}}} =
  \frac{1}{e^{\beta_{\text{E/I}}}} =
  e^{-0.5805} =
  0.5596
\]</span> 95% CI for the conditional odds ratio between I/E and the response: <span class="math display">\[
  \left[\frac{1}{2.7400}, \frac{1}{1.1722} \right] =
  [0.3650, 0.8531]
\]</span> With 95% confidence, the true value of the conditional odds ratio between I/E and the response lies between 0.3650 and 0.8531 based on the sample.</p>
</div>
<div id="e.-1" class="section level3">
<h3>e.</h3>
<pre class="r"><code>logit_reg_4.17e &lt;- glm(
  Alcohol ~ `T/F`
  ,data = myers_data
  ,family = &quot;binomial&quot;
)
summary(logit_reg_4.17e)</code></pre>
<pre><code>## 
## Call:
## glm(formula = Alcohol ~ `T/F`, family = &quot;binomial&quot;, data = myers_data)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -0.5112  -0.5112  -0.3917  -0.3917   2.2829  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  -2.5291     0.1500 -16.862  &lt; 2e-16 ***
## `T/F`         0.5601     0.2139   2.619  0.00883 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 646.83  on 1049  degrees of freedom
## Residual deviance: 640.02  on 1048  degrees of freedom
## AIC: 644.02
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<pre class="r"><code>anova(logit_reg_4.17e, logit_reg_4.17a, test = &quot;Chisq&quot;)</code></pre>
<pre><code>## Analysis of Deviance Table
## 
## Model 1: Alcohol ~ `T/F`
## Model 2: Alcohol ~ `E/I` + `T/F`
##   Resid. Df Resid. Dev Df Deviance Pr(&gt;Chi)   
## 1      1048     640.02                        
## 2      1047     632.74  1   7.2847 0.006955 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Using the likelihood ratio test, comparing the two models, a p-value of 0.006955 is observed. So at <span class="math inline">\(\alpha=0.05\)</span> the null hypothesis of equivalent explained variance is rejected, and it can be assumed that E/I plays a statistically significant effect based on the sample.</p>
</div>
</div>
<div id="section-4" class="section level2">
<h2>4.19</h2>
<pre class="r"><code>logit_reg_4.19 &lt;- function(Gender, Religion, Political){
  log_odds &lt;-
    -0.11 + 
    if_else(Gender == &quot;M&quot;, 0.0, 0.16) +
    if_else(Religion == &quot;J&quot;, 0.0, if_else(Religion == &quot;C&quot;, -0.66, -0.57)) +
    if_else(Political == &quot;I&quot;, 0.0, if_else(Political == &quot;R&quot;, -1.67, 0.84))
  log_odds
}</code></pre>
<div id="a.-3" class="section level3">
<h3>a.</h3>
<p><span class="math display">\[
  OR_{\text{Gender}} =
  e^{\hat{\beta}_{1}^{G} - \hat{\beta}_{2}^{G}} =
  e^{0.16 - 0} = 
  1.1735
\]</span> Holding all else equal, the odds of supporting legalized abortion increases on average by a multiplicative factor of 1.1735 for females vs. males.</p>
</div>
<div id="b.-3" class="section level3">
<h3>b.</h3>
<pre class="r"><code>log_odds_MCR &lt;- logit_reg_4.19(Gender = &quot;M&quot;, Religion = &quot;C&quot;, Political = &quot;R&quot;)
prob_MCR &lt;- exp(log_odds_MCR)/(1 + exp(log_odds_MCR))
prob_MCR</code></pre>
<pre><code>## [1] 0.08017291</code></pre>
<pre class="r"><code>log_odds_FJD &lt;- logit_reg_4.19(Gender = &quot;F&quot;, Religion = &quot;J&quot;, Political = &quot;D&quot;)
prob_FJD &lt;- exp(log_odds_FJD)/(1 + exp(log_odds_FJD))
prob_FJD</code></pre>
<pre><code>## [1] 0.7088902</code></pre>
</div>
<div id="c.-3" class="section level3">
<h3>c.</h3>
<p><span class="math display">\[
  \hat{\beta}_{2}^{G} = 
  0.16 \implies
  OR_{\text{Gender}} =
  e^{\hat{\beta}_{1}^{G} - \hat{\beta}_{2}^{G}} =
  e^{0 - 0.16} =
  0.8521
\]</span> Holding all else equal, the odds of supporting legalized abortion decreases on average by a multiplicative factor of 0.8521 for males vs. females.</p>
</div>
<div id="d.-2" class="section level3">
<h3>d.</h3>
<p><span class="math display">\[
  \hat{\beta}_{1}^{G} + \hat{\beta}_{2}^{G} =
  0,
  \hat{\beta}_{1}^{G} - \hat{\beta}_{2}^{G} =
  0.16 \implies
  \hat{\beta}_{1}^{G} =
  0.08, 
  \hat{\beta}_{2}^{G} =
  -0.08 \implies
\]</span> <span class="math display">\[
  OR_{\text{Gender}} =
  e^{0.08-(-0.08)} =
  e^{0.16} =
  1.1735
\]</span></p>
</div>
</div>
<div id="section-5" class="section level2">
<h2>4.21</h2>
<div id="a.-4" class="section level3">
<h3>a.</h3>
<p>The odds in favour of getting condoms increases on average by a multiplicative factor of 4.04 for those who wached the video, vs. those who didn’t based on the sample. With 95% confidence the true value of said odds ratio is between 1.17 and 13.9.</p>
</div>
<div id="b.-4" class="section level3">
<h3>b.</h3>
<p><span class="math display">\[
  \ln\left( \theta_{\text{Condoms}} \right) =
  \hat{\beta_{0}} + \ln 4.04x_{\text{Group}} + \ln 1.38x_{\text{Gender}} + \ln 5.82x_{\text{SES}} + \ln 3.22x_{\text{Num. of Partners}} \implies
\]</span> <span class="math display">\[
  \ln\left( \theta_{\text{Condoms}} \right) =
  \hat{\beta_{0}} + 1.40x_{\text{Group}} + 0.32x_{\text{Gender}} + 1.76x_{\text{SES}} + 1.17x_{\text{Num. of Partners}}
\]</span></p>
</div>
<div id="c.-4" class="section level3">
<h3>c.</h3>
<p><span class="math display">\[
  \hat{\beta}_{\text{Gender}} =
  \frac{\ln 1.23 + \ln 12.88}{2} =
  1.3813 \approx
  1.38 \neq
  \ln 1.38 =
  0.3221 \implies 
\]</span> <span class="math display">\[
  OR_{\text{Gender}} =
  e^{1.38} =
  3.9803 \approx
  3.98
\]</span> Therefore, if the confidence interval is correct the log odds ratio for gender must be 1.38, giving an estimated odds ratio of 3.98.</p>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
