<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />


<meta name="author" content="Scott Graham" />


<title>Week 02 Questions</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/lumen.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-1.1/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-1.1/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs && document.readyState && document.readyState === "complete") {
   window.setTimeout(function() {
      hljs.initHighlighting();
   }, 0);
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 54px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 59px;
  margin-top: -59px;
}

.section h2 {
  padding-top: 59px;
  margin-top: -59px;
}
.section h3 {
  padding-top: 59px;
  margin-top: -59px;
}
.section h4 {
  padding-top: 59px;
  margin-top: -59px;
}
.section h5 {
  padding-top: 59px;
  margin-top: -59px;
}
.section h6 {
  padding-top: 59px;
  margin-top: -59px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>




<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
  padding-left: 25px;
  text-indent: 0;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">STAT 541 Questions</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="../../">Home</a>
</li>
<li>
  <a href="Week_01_Questions.html">Week 01</a>
</li>
<li>
  <a href="Week_02_Questions.html">Week 02</a>
</li>
<li>
  <a href="Week_03_Questions.html">Week 03</a>
</li>
<li>
  <a href="Week_04_Questions.html">Week 04</a>
</li>
<li>
  <a href="Week_05_Questions.html">Week 05</a>
</li>
<li>
  <a href="Week_06_Questions.html">Week 06</a>
</li>
<li>
  <a href="Week_07_Questions.html">Week 07</a>
</li>
<li>
  <a href="Week_08_Questions.html">Week 08</a>
</li>
<li>
  <a href="Week_10_Questions.html">Week 10</a>
</li>
<li>
  <a href="Week_11_Questions.html">Week 11</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">

<div class="btn-group pull-right">
<button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Week 02 Questions</h1>
<h4 class="author"><em>Scott Graham</em></h4>
<h4 class="date"><em>Sepetember 22, 2017</em></h4>

</div>


<p><span class="math display">\[
  \newcommand{\Prob}{\operatorname{P}}
  \newcommand{\E}{\operatorname{E}}
  \newcommand{\Var}{\operatorname{Var}}
  \newcommand{\Cov}{\operatorname{Cov}}
  \newcommand{\se}{\operatorname{se}}
  \newcommand{\re}{\operatorname{re}}
  \newcommand{\ybar}{{\overline{Y}}}
  \newcommand{\phat}{{\hat{p}}}
  \newcommand{\that}{{\hat{T}}}
  \newcommand{\med}{{\tilde{Y}}}
\]</span></p>
<div id="section" class="section level2">
<h2>2.01</h2>
<div id="a." class="section level3">
<h3>a.</h3>
<p><span class="math display">\[
  \Prob ( - | C ) = \frac{1}{4},
  \Prob ( + | \bar{C} ) = \frac{2}{3}
\]</span></p>
</div>
<div id="b." class="section level3">
<h3>b.</h3>
<p><span class="math display">\[
  \Prob ( + | C ) = 
  1 - \Prob ( - | C ) =
  1 - \frac{1}{4} =
  \frac{3}{4}
\]</span></p>
</div>
<div id="c." class="section level3">
<h3>c.</h3>
<pre class="r"><code>probs &lt;- matrix(c(0.01*3/4, 0.99*2/3, 0.01*1/4, 0.99*1/3), nrow = 2, ncol = 2)
rownames(probs) &lt;- c(&quot;C&quot;, &quot;CBar&quot;)
colnames(probs) &lt;- c(&quot;+&quot;, &quot;-&quot;)
probs</code></pre>
<pre><code>##           +      -
## C    0.0075 0.0025
## CBar 0.6600 0.3300</code></pre>
<pre class="r"><code>sum_rows &lt;- c()
for (i in 1:2){
  sum_rows[i] &lt;- sum(probs[i, ])
}
sum_cols &lt;- c()
for (j in 1:2){
  sum_cols[j] &lt;- sum(probs[, j])
}
sum_rows</code></pre>
<pre><code>## [1] 0.01 0.99</code></pre>
<pre class="r"><code>sum_cols</code></pre>
<pre><code>## [1] 0.6675 0.3325</code></pre>
</div>
<div id="d." class="section level3">
<h3>d.</h3>
<p>From the “sum_cols” variable: <span class="math display">\[
  \Prob(+) = 0.6675,
  \Prob(-) = 0.3325
\]</span> <span class="math display">\[
  \text{Test Result} \sim \operatorname{Bernoulli}(p = 0.6675)
\]</span></p>
</div>
<div id="e." class="section level3">
<h3>e.</h3>
<p><span class="math display">\[
  \Prob(C|+) = 
  \frac{\Prob(+|C) \Prob(C)}{\Prob(+)} =
  \frac{\frac{3}{4} \times 0.1}{0.6675} =
\]</span></p>
<pre class="r"><code>  3/4*sum_rows[1]/sum_cols[1]</code></pre>
<pre><code>## [1] 0.01123596</code></pre>
</div>
</div>
<div id="section-1" class="section level2">
<h2>2.05</h2>
<div id="a.-1" class="section level3">
<h3>a.</h3>
<p>Since we are dealing with likelihood, the 1.7 is the relative risk.</p>
</div>
<div id="b.-1" class="section level3">
<h3>b.</h3>
<p>Let C be having cancer, and D taking the drug: <span class="math display">\[
  \Prob(C|D) = 0.55\Prob(C|D^{c}) \implies
  RR = \frac{0.55}{1} = 0.55
\]</span> Similarily <span class="math display">\[
  RR = \frac{1}{0.55} = 1.\overline{81}
\]</span></p>
</div>
</div>
<div id="section-2" class="section level2">
<h2>2.07</h2>
<div id="a.-2" class="section level3">
<h3>a.</h3>
<p>With an odds ratio, we aren’t directly measuring the probability of an event, merely its odds. The correct iterpretation would be the odds of a female surviving is 11.4 times that of a male.</p>
</div>
<div id="b.-2" class="section level3">
<h3>b.</h3>
<p><span class="math display">\[
  \Prob(S|F) = 2.9\Prob(D|F) \implies
  1 = 2.9\Prob(D|F) + \Prob(D|F) \implies
  \Prob(D|F) = \frac{10}{39} \implies
  \Prob(S|F) = \frac{29}{39}
\]</span> <span class="math display">\[
  \frac{\Prob(S|M)}{\Prob(D|M)} =
  \frac{2.9}{11.4} =
  \frac{29}{114} \implies
  1 = \frac{29}{114}\Prob(D|M) + \Prob(D|M) \implies
  \Prob(D|M) = \frac{114}{143} \implies
\]</span> <span class="math display">\[
  \Prob(S|M) = \frac{29}{143}
\]</span></p>
</div>
<div id="c.-1" class="section level3">
<h3>c.</h3>
<p><span class="math display">\[
  RR = 
  \frac{\Prob(S|F)}{\Prob(S|M)} =
  \frac{\frac{29}{39}}{\frac{29}{143}} =
  \frac{143}{39}
\]</span> The probability of survival for females was <span class="math inline">\(3.\overline{66}\)</span> times that for males.</p>
</div>
</div>
<div id="section-3" class="section level2">
<h2>2.11</h2>
<div id="a.-3" class="section level3">
<h3>a.</h3>
<p>The difference in proportions for lung cancer is: <span class="math display">\[
  \phat_{LC|S} - \phat_{LC|NS} = 
  0.00140 - 0.00010 =
  0.00130
\]</span> So the probability of dieing from lung cancer increases by 0.0013 per year if one smokes.</p>
<p>The difference in proportions for heart disease is: <span class="math display">\[
  \phat_{HD|S} - \phat_{HD|NS} = 
  0.00669 - 0.00413 =
  0.00256
\]</span> So the probability of dieing from heart disease increases by 0.00256 per year if one smokes.</p>
<p><span class="math display">\[
  RR_{LC} =
  \frac{\phat_{LC|S}}{\phat_{LC|NS}} =
  \frac{0.00140}{0.00010} = 
  14
\]</span> So the probability of dieing from lung cancer is 14 times higher per year for smokers vs. non-smokers.</p>
<p><span class="math display">\[
  RR_{HD} =
  \frac{\phat_{HD|S}}{\phat_{HD|NS}} =
  \frac{0.00669}{0.00413} = 
  1.619855
\]</span> So the probability of dieing from heart disease is 1.619855 times higher per year for smokers vs. non-smokers.</p>
<p><span class="math display">\[
  OR_{LC} =
  \frac{\frac{\phat_{LC|S}}{1-\phat_{LC|S}}}{\frac{\phat_{LC|NS}}{1-\phat_{LC|NS}}} =
  \frac{\frac{0.00140}{1-0.00140}}{\frac{0.00010}{1-0.00010}} =
  14.01823
\]</span> So the odds of dieing from lung cancer is 14.01823 times higher per year for smokers vs. non-smokers.</p>
<p><span class="math display">\[
  OR_{HD} =
  \frac{\frac{\phat_{HD|S}}{1-\phat_{HD|S}}}{\frac{\phat_{HD|NS}}{1-\phat_{HD|NS}}} =
  \frac{\frac{0.00669}{1-0.00669}}{\frac{0.00413}{1-0.00413}} =
  1.624029
\]</span> So the odds of dieing from heart disease is 1.624029 times higher per year for smokers vs. non-smokers.</p>
</div>
<div id="b.-3" class="section level3">
<h3>b.</h3>
<p>Lung cancer is more strongly related to one’s smoking habits compared to Heart Disease. While its difference in probability of death is smaller than heart disease, the likelihood and odds are both much greater than their heart disease counterparts.</p>
</div>
</div>
<div id="section-4" class="section level2">
<h2>2.23</h2>
<p>Let <span class="math inline">\(\alpha = 0.05\)</span>. <span class="math display">\[
  H_{0}: \text{Highest Degree and Religious Beliefs are independent}
\]</span> <span class="math display">\[
  H_{1}: \text{Highest Degree and Religious Beliefs are dependent}
\]</span></p>
<p>P-Value:</p>
<pre class="r"><code>edu_rel_tbl &lt;- matrix(c(178, 570, 138, 138, 648, 252, 108, 442, 252), nrow = 3, ncol = 3)
colnames(edu_rel_tbl) &lt;- c(&quot;Fundamentalist&quot;, &quot;Moderate&quot;, &quot;Liberal&quot;)
rownames(edu_rel_tbl) &lt;- c(&quot;&lt; High School&quot;, &quot;High School or Junior College&quot;, &quot;Bachelor or Graduate&quot;)
chisq.test(edu_rel_tbl, correct = FALSE)</code></pre>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  edu_rel_tbl
## X-squared = 69.157, df = 4, p-value = 3.42e-14</code></pre>
<p>Because our p-value is <span class="math inline">\(&lt;\alpha\)</span>, we reject our null hypothesis of independence, and assume some sort of dependency based on our sample.</p>
<pre class="r"><code>chisq.test(edu_rel_tbl, correct = FALSE)$stdres</code></pre>
<pre><code>##                               Fundamentalist   Moderate   Liberal
## &lt; High School                       4.534918 -2.5521511 -1.941705
## High School or Junior College       2.553268  1.2859224 -3.994697
## Bachelor or Graduate               -6.809750  0.7009713  6.252547</code></pre>
<p>The large standarized residuals for the Fundamentalist and Liberal categories shows that their may exist some relation between education and those categories, hence their may be dependency.</p>
</div>
<div id="section-5" class="section level2">
<h2>2.27</h2>
<div id="a.-4" class="section level3">
<h3>a.</h3>
<p>Let <span class="math inline">\(\alpha = 0.05\)</span>. <span class="math display">\[
  H_{0}: \text{Family Income and Aspirations are independent}
\]</span> <span class="math display">\[
  H_{1}: \text{Family Income and Aspirations are dependent}
\]</span></p>
<pre class="r"><code>aspirations_tbl &lt;- matrix(c(9, 44, 13, 10, 11, 52, 23, 22, 9, 41, 12, 27), nrow = 4, ncol = 3)
colnames(aspirations_tbl) &lt;- c(&quot;L&quot;, &quot;M&quot;, &quot;H&quot;)
rownames(aspirations_tbl) &lt;- c(&quot;Some HS&quot;, &quot;Graduate HS&quot;, &quot;Some College&quot;, &quot;Graduate College&quot;)
aspirations_tbl</code></pre>
<pre><code>##                   L  M  H
## Some HS           9 11  9
## Graduate HS      44 52 41
## Some College     13 23 12
## Graduate College 10 22 27</code></pre>
<pre class="r"><code>chisq.test(aspirations_tbl, correct = FALSE)</code></pre>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  aspirations_tbl
## X-squared = 8.8709, df = 6, p-value = 0.181</code></pre>
<pre class="r"><code>chisq.test(aspirations_tbl, correct = FALSE)$expected</code></pre>
<pre><code>##                         L        M         H
## Some HS           8.07326 11.47253  9.454212
## Graduate HS      38.13919 54.19780 44.663004
## Some College     13.36264 18.98901 15.648352
## Graduate College 16.42491 23.34066 19.234432</code></pre>
<p>At that level, we fail to reject our null hypothesis of independence, based on our sample. However, the family income levels are ordinal instead of purely categorical, our tests may not be accurate.</p>
</div>
<div id="b.-4" class="section level3">
<h3>b.</h3>
<pre class="r"><code>chisq.test(aspirations_tbl, correct = FALSE)$stdres</code></pre>
<pre><code>##                           L          M          H
## Some HS           0.4061328 -0.1898118 -0.1903291
## Graduate HS       1.5828205 -0.5440627 -0.9459053
## Some College     -0.1286367  1.3041565 -1.2374420
## Graduate College -2.1078423 -0.4031584  2.4360173</code></pre>
<p>For low income families, we see a fair bit less number of students who aspire to graduate from college than what we would expect if they were independent. The opposite is true for high income families, where a fair bit more number of students expect to graduate from college, than we’d expect under the null hypothesis. For medium income families, our standardized residuals are all fairly small, so there may not be dependency. Note that all our standardized residuals are between <span class="math inline">\([-2.5, 2.5]\)</span>, so most likely no strong dependencies exists based on this sample.</p>
</div>
<div id="c.-2" class="section level3">
<h3>c.</h3>
<pre class="r"><code>library(coin)</code></pre>
<pre><code>## Loading required package: survival</code></pre>
<pre class="r"><code>aspirations_tbl &lt;- as.table(aspirations_tbl)
lbl_test(aspirations_tbl)</code></pre>
<pre><code>## 
##  Asymptotic Linear-by-Linear Association Test
## 
## data:  Var2 (ordered) by
##   Var1 (Some HS &lt; Graduate HS &lt; Some College &lt; Graduate College)
## Z = 2.1792, p-value = 0.02932
## alternative hypothesis: two.sided</code></pre>
<pre class="r"><code>pchisq(statistic(lbl_test(aspirations_tbl))^2, 1, lower.tail = FALSE)</code></pre>
<pre><code>##            
## 0.02931658</code></pre>
<p>Since our p-value is <span class="math inline">\(&lt;\alpha\)</span>, we reject our null hypothesis, and assume some dependency based on the sample.</p>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
